### ISSUE TITLE
No error but returning an empty .xlsx

### ISSUE THREAD

**Issue by SensationSama** [dwqs/js2excel#2]
Normally I would use a more supported library to know it works for sure but there's a lack of options. Is the current build passing? Here's the data I used.
```
testData = [{
        "name": 'aa',
        "otherField": 55,
      }, {
        "name": 'bb',
        "otherField": 22,
      },]

 try {
        json2excel({
          testData,
          name: 'user-info-data',
          formateDate: 'yyyy/mm/dd'
        });
      } catch (e) {
        console.error('export error');
      }
```

Also I think the doc is missing a comma after `data`
```
try {
    json2excel({
        data
        name: 'user-info-data',
        formateDate: 'yyyy/mm/dd'
    });
} catch (e) {
    console.error('export error');
}
```

..and is `formate` in `formateData` a typo?

Thanks

**Comment by dwqs** [comment]
It's ok when i test it:

![image](https://user-images.githubusercontent.com/7871813/41016403-aaf333c2-6981-11e8-955a-a5b6cb3005c6.png)

**Comment by dwqs** [comment]
No response too long
