### ISSUE TITLE
blob is not defined

### ISSUE THREAD

**Issue by jchan-1024** [dwqs/js2excel#3]
i try to run the example in the description but i get this error "blob is not defined",

is a tyscript file and i importing by commonjs method, 

if i try to import is as es6 with 

`import excel  from "js2excel";`

this give me this error :

Cannot read property 'json2excel' of undefined

**Comment by dwqs** [comment]
Maybe your browser doesn't support [Blob](https://caniuse.com/#search=Blob)

try import * as excel from "js2excel" or import {json2excel, excel2json} from 'js2excel';

**Comment by dwqs** [comment]
No response too long
